# Generated by Django 4.0.6 on 2022-07-31 14:14

from django.db import migrations

def populate_status(apps, schemaeditor):
    statuses = {
        "published": "Content that is displayed on the site",
        "pending_review": "Content that has not yet been validated by an editor",
        "revision_requested": "Content that requires modifications based on an editorial review",
        "denied": "Content that will not be displayed on the site",
        "draft": "A work in progress"
    }
    Status = apps.get_model("articles","Status")
    for name, desc in statuses.item():
        status_obj = Status(name=name, description=desc)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_status_article_status'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
